In [16]:
def save(data):
    with open('img_out.dat', 'w', encoding='utf-8') as f:
        f.write(data)

In [23]:
with open('MVIMG_20220621_174330.jpg', 'rb') as f:
    img = f.read()
save(img.__str__())

In [45]:
from PIL import Image
img = Image.open('MVIMG_20220621_174330.jpg')
# img.show()
print(img.mode, img.size, img.format)

import numpy as np
array = np.array(img)
print(array.shape)
print(array[0])


# np.save('npOut.txt', array)
# save(str(array))
# with open('npOut.dat', 'w', encoding='utf-8') as fp:
#     array.tofile(fp)

RGB (4080, 3060) JPEG
(3060, 4080, 3)
[[ 79 155 230]
 [ 79 155 230]
 [ 79 155 230]
 ...
 [113 172 238]
 [113 172 238]
 [114 173 239]]
